/*
    File that contains auth action types
*/
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const ON_LOGIN_EMAIL_CHANGE = 'ON_LOGIN_EMAIL_CHANGE';
export const ON_LOGIN_PASSWORD_CHANGE = 'ON_LOGIN_PASSWORD_CHANGE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ON_BANK_NAME_CHANGE = 'ON_BANK_NAME_CHANGE';
export const ON_BANK_IBAN_CHANGE = 'ON_BANK_IBAN_CHANGE';
export const ON_BANK_ACCOUNT_CHANGE = 'ON_BANK_ACCOUNT_CHANGE';
export const ON_BANK_CODE_CHANGE = 'ON_BANK_CODE_CHANGE';
export const ON_BANK_ADDRESS_CHANGE = 'ON_BANK_ADDRESS_CHANGE';

export const ADD_BANK_LOADING = 'ADD_BANK_LOADING';
export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS';
export const ADD_BANK_FAILED = 'ADD_BANK_FAILED';

export const UPDATE_BANK_LOADING = 'UPDATE_BANK_LOADING';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_FAILED = 'UPDATE_BANK_FAILED';

export const REMOVE_BANK_LOADING = 'REMOVE_BANK_LOADING';
export const REMOVE_BANK_SUCCESS = 'REMOVE_BANK_SUCCESS';
export const REMOVE_BANK_FAILED = 'REMOVE_BANK_FAILED';

export const CHECK_USER_LOADING = 'CHECK_USER_LOADING';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILED = 'CHECK_USER_FAILED';


export const ON_DOC_TITLE_CHANGE = 'ON_DOC_TITLE_CHANGE';
export const ON_DOC_DESCRIPTION_CHANGE = 'ON_DOC_DESCRIPTION_CHANGE';
export const ON_DOC_FILE_UPLOAD = 'ON_DOC_FILE_UPLOAD';
export const ON_DOC_FILE_REMOVE = 'ON_DOC_FILE_REMOVE';

export const ADD_DOC_LOADING = 'ADD_DOC_LOADING';
export const ADD_DOC_SUCCESS = 'ADD_DOC_SUCCESS';
export const ADD_DOC_FAILED = 'ADD_DOC_FAILED';

export const UPDATE_DOC_LOADING = 'UPDATE_DOC_LOADING';
export const UPDATE_DOC_SUCCESS = 'UPDATE_DOC_SUCCESS';
export const UPDATE_DOC_FAILED = 'UPDATE_DOC_FAILED';

export const REMOVE_DOC_LOADING = 'REMOVE_DOC_LOADING';
export const REMOVE_DOC_SUCCESS = 'REMOVE_DOC_SUCCESS';
export const REMOVE_DOC_FAILED = 'REMOVE_DOC_FAILED';


export const ON_VENDOR_NAME_CHANGE = 'ON_VENDOR_NAME_CHANGE';
export const ON_DISPLAY_NAME_CHANGE = 'ON_DISPLAY_NAME_CHANGE';
export const ON_LICENSE_NUMBER_CHANGE = 'ON_LICENSE_NUMBER_CHANGE';
export const ON_CELL_NUMBER_CHANGE = 'ON_CELL_NUMBER_CHANGE';
export const ON_VENDOR_SITE_CHANGE = 'ON_VENDOR_SITE_CHANGE';
export const ON_EMAIL_CHANGE = 'ON_EMAIL_CHANGE';
export const ON_REMARKS_CHANGE = 'ON_REMARKS_CHANGE';
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const LOGOUT = 'LOGOUT';

export const ON_SIGNUP_VENDOR_NAME_CHANGE = 'ON_SIGNUP_VENDOR_NAME_CHANGE';
export const ON_SIGNUP_DISPLAY_NAME_CHANGE = 'ON_SIGNUP_DISPLAY_NAME_CHANGE';
export const ON_SIGNUP_CELL_NUMBER_CHANGE = 'ON_SIGNUP_CELL_NUMBER_CHANGE';
export const ON_SIGNUP_VENDOR_SITE_CHANGE = 'ON_SIGNUP_VENDOR_SITE_CHANGE';
export const ON_SIGNUP_EMAIL_CHANGE = 'ON_SIGNUP_EMAIL_CHANGE';
export const SIGNUP_INFO_LOADING = 'SIGNUP_INFO_LOADING';
export const SIGNUP_INFO_SUCCESS = 'SIGNUP_INFO_SUCCESS';
export const SIGNUP_INFO_FAILED = 'SIGNUP_INFO_FAILED';

export const ON_SIGNUP_OTP_CHANGE = 'ON_SIGNUP_OTP_CHANGE';
export const SIGNUP_OTP_LOADING = 'SIGNUP_OTP_LOADING';
export const SIGNUP_OTP_SUCCESS = 'SIGNUP_OTP_SUCCESS';
export const SIGNUP_OTP_FAILED = 'SIGNUP_OTP_FAILED';

export const ON_SIGNUP_PASSWORD_CHANGE = 'ON_SIGNUP_PASSWORD_CHANGE';
export const ON_SIGNUP_CONFIRM_PASSWORD_CHANGE = 'ON_SIGNUP_CONFIRM_PASSWORD_CHANGE';
export const SIGNUP_SET_PASS_LOADING = 'SIGNUP_SET_PASS_LOADING';
export const SIGNUP_SET_PASS_SUCCESS = 'SIGNUP_SET_PASS_SUCCESS';
export const SIGNUP_SET_PASS_FAILED = 'SIGNUP_SET_PASS_FAILED';

export const ON_RESET_EMAIL_CHANGE = 'ON_RESET_EMAIL_CHANGE';
export const RESET_LOADING = 'RESET_LOADING';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILED = 'RESET_FAILED';

export const ON_RESET_OTP_CHANGE = 'ON_RESET_OTP_CHANGE';
export const RESET_OTP_LOADING = 'RESET_OTP_LOADING';
export const RESET_OTP_SUCCESS = 'RESET_OTP_SUCCESS';
export const RESET_OTP_FAILED = 'RESET_OTP_FAILED';

export const ON_RESET_PASSWORD_CHANGE = 'ON_RESET_PASSWORD_CHANGE';
export const ON_RESET_CONFIRM_PASSWORD_CHANGE = 'ON_RESET_CONFIRM_PASSWORD_CHANGE';
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSOWRD_SUCCESS = 'RESET_PASSOWRD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const RESEND_OTP_LOADING = 'RESEND_OTP_LOADING';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILED = 'RESEND_OTP_FAILED';

export const LOGO_UPLOAD_LOADING = 'PROFILE_UPLOAD_LOADING';
export const ON_PROFILE_LOGO_UPLOAD = 'ON_PROFILE_LOGO_UPLOAD';

export const ON_LOGO_CHANGE = 'ON_LOGO_CHANGE';

export const LOGO_REMOVE_LOADING = 'PROFILE_REMOVE_LOADING';
export const ON_PROFILE_LOGO_REMOVE = 'ON_PROFILE_LOGO_REMOVE';

export const FETCH_NOTIFICATION_LOADING = 'FETCH_NOTIFICATION_LOADING';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILED = 'FETCH_NOTIFICATION_FAILED';

export const SET_FCM_SUCCESS = "SET_FCM_SUCCESS";
export const SET_FCM_FAILED = "SET_FCM_FAILED";